#!/usr/bin/env bash
# =============================================================================
# agents-md-gen.sh — generate the root AGENTS.md (2026 cross-tool lingua franca)
#
# Sibling of butterfreezone-gen.sh (which emits the codebase MAP). This emits the
# GOVERNANCE + CONVENTIONS surface read first by 25+ agent tools. OKF/ICM adoption
# cycle, Sprint 2 (rec #3). BUTTERFREEZONE.md is retained as a separate artifact.
#
# DETERMINISM CONTRACT: output is a pure function of its inputs
#   (.claude/data/golden-path.json, .claude/commands/*.md, the governance tables
#    in .claude/loa/CLAUDE.loa.md). No wall-clock timestamp / head_sha is emitted,
#   so the file changes ONLY when an input changes — keeping the drift gate stable.
#
# Flags: --check (regen + diff vs committed AGENTS.md + README doc-claim consistency)
#        --dry-run (print to stdout)  --output PATH  --json (metadata to stderr)
#
# --check closes: #1132 (Quick-Start Golden-Path block drift, BLOCK-SCOPED),
#   #1135 (command-count generated verification, BOTH README count claims),
#   #1143 / #1149 (doc claims machine-verified). NOTE: #1130/#1124 (version-surface
#   parity) are NOT covered here — deferred (separate version surface).
# =============================================================================
export LC_ALL=C
export TZ=UTC
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SCRIPT_VERSION="1.1.0"
source "${SCRIPT_DIR}/compat-lib.sh"

GOLDEN_JSON="${PROJECT_ROOT}/.claude/data/golden-path.json"
COMMANDS_DIR="${PROJECT_ROOT}/.claude/commands"
GOV_SRC="${PROJECT_ROOT}/.claude/loa/CLAUDE.loa.md"
README="${PROJECT_ROOT}/README.md"
OUT_DEFAULT="${PROJECT_ROOT}/AGENTS.md"

MODE="write"; OUT="${OUT_DEFAULT}"; EMIT_JSON=0

usage() { sed -n '2,24p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --check)   MODE="check" ;;
      --dry-run) MODE="dry-run" ;;
      --json)    EMIT_JSON=1 ;;
      --output)  OUT="$2"; shift ;;
      -h|--help) usage; exit 0 ;;
      *) echo "agents-md-gen: unknown arg: $1" >&2; exit 2 ;;
    esac
    shift
  done
}

# --- inputs (jq for JSON; LC_ALL=C grep for governance — all deterministic) ---
require_jq() { command -v jq >/dev/null 2>&1 || { echo "agents-md-gen: jq required" >&2; exit 3; }; }
golden_list()   { jq -r '.golden[]' "${GOLDEN_JSON}" | tr '\n' ' ' | sed 's/ $//'; }
excluded_count(){ jq -r '.excluded_from_count | length' "${GOLDEN_JSON}"; }
total_command_count() {
  local total; total=$(find "${COMMANDS_DIR}" -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')
  echo $(( total - $(excluded_count) ))
}
governance_rules() {  # arg: NEVER|ALWAYS|MAY — first column of matching table rows, source order, deduped
  grep -hE "^\| $1 " "${GOV_SRC}" 2>/dev/null \
    | sed -E 's/^\| //; s/ \|.*$//; s/[[:space:]]+$//' | awk '!seen[$0]++'
}
# The README Quick Start fenced block (lines after the "# 5 commands…" marker, up to the closing fence)
readme_quickstart_block() {
  awk '/# 5 commands\. Full development cycle\./{f=1; next} f && /^```/{exit} f{print}' "${README}"
}

emit() {
  local golden total; golden="$(golden_list)"; total="$(total_command_count)"
  cat <<'HDR'
<!-- generated by agents-md-gen.sh — DO NOT EDIT. Regenerate: bash .claude/scripts/agents-md-gen.sh
     This is loa's OWN generated governance projection, NOT an operator/Moltbot marker
     (see .claude/skills/autonomous-agent/resources/operator-detection.md). -->

# AGENTS.md — loa

> Agent-driven software-development framework. This file is the portable, tool-agnostic
> projection of loa's governance and conventions, read first by AGENTS.md-aware tools.
> Tool-specific depth lives in `CLAUDE.md` / `.claude/`. Source of truth: those files —
> this is a generated summary.

## Quick Start
HDR
  echo
  echo "Primary interface: ${total}+ commands fronted by **5 Golden Path commands** (zero-arg)."
  echo
  echo '```'
  for g in ${golden}; do printf '/%s\n' "$g"; done
  echo '```'
  echo
  echo "- \`/loa\` — where am I? status + health + next step"
  echo "- \`/plan\` — requirements → architecture → sprints"
  echo "- \`/build\` — implement the current sprint"
  echo "- \`/review\` — code review + security audit"
  echo "- \`/ship\` — deploy + archive the cycle"
  echo
  echo "## Commands"
  echo
  local glist; glist="$(echo "${golden}" | sed 's/ /`, `\//g; s/^/`\//; s/$/`/')"
  echo "**5 Golden Path commands** (${glist}) front **${total} total commands** (truenames). See \`PROCESS.md\` for the full list; type \`/loa\` for orientation."
  echo
  echo "## Project Governance"
  echo
  echo "Precedence: **NEVER > MUST > ALWAYS > SHOULD > MAY.** These are mechanically enforced (harness \`disallowed-tools\` + PreToolUse hooks), not advisory."
  echo
  local kw rule
  for kw in NEVER ALWAYS MAY; do
    if governance_rules "$kw" | grep -q .; then
      echo "**${kw}**"
      governance_rules "$kw" | while IFS= read -r rule; do [[ -n "$rule" ]] && echo "- ${rule}"; done
      echo
    fi
  done
  cat <<'ZONES'
### Three-Zone model
| Zone | Path | Rule |
|------|------|------|
| System | `.claude/` | NEVER edit directly (use `.claude/overrides/` or `.loa.config.yaml`) |
| State | `grimoires/`, `.beads/`, `.ck/`, `.run/` | Read/Write |
| App | `src/`, `lib/`, `app/` | Confirm writes |

## Conventions
- **Default PR reviewer:** @janitooor (always request review).
- **Branch from `main`**; never commit directly to the default branch.
- **Commit trailer:** end commit messages with `Co-Authored-By: Claude <noreply@anthropic.com>`.
- **Beads-first:** task lifecycle is tracked via `br` (beads_rust); it is the source of truth, not ad-hoc TODOs.

## Context Intake (read FIRST)
Before any substantive work, consult the known-failures **index**, not the full log. If `known_failures.surface_at_session_start` is true the `.claude/hooks/loa-kf-surface.sh` SessionStart hook has already printed a symptom → KF table into context; otherwise run `bash .claude/scripts/grimoire-index.sh` and read the `## kf` section of `grimoires/loa/INDEX.md`. Open `grimoires/loa/known-failures.md` at a matching `## KF-NNN:` heading only for its **Reading guide** (full read only when authoring or repairing an entry). Recurrence count ≥ 3 means a failure class is structural; route through the upstream issue rather than retrying listed dead-ends.
ZONES
}

# --- README doc-claim consistency (the folded #1132/#1135/#1143/#1149 gate) ---
readme_consistency() {
  local rc=0 total g block; total="$(total_command_count)"
  # #1132 — BLOCK-SCOPED: every Golden Path command must appear in the Quick Start block itself.
  block="$(readme_quickstart_block)"
  for g in $(golden_list); do
    grep -qE "^/${g}\b" <<<"$block" || { echo "::error::[DRIFT-AGENTS-MD] #1132: README Quick Start block missing /${g}" >&2; rc=1; }
  done
  # #1135 — anchored, BOTH README count claims must equal the computed total.
  grep -qE "\*\*${total} total commands\.\*\*" "${README}" || { echo "::error::[DRIFT-AGENTS-MD] #1135: README '**N total commands.**' != computed ${total}" >&2; rc=1; }
  grep -qE "\b${total} slash commands\b" "${README}"       || { echo "::error::[DRIFT-AGENTS-MD] #1135: README 'N slash commands' != computed ${total}" >&2; rc=1; }
  return $rc
}

# --- main ---
parse_args "$@"
require_jq
TMP="$(mktemp)"; trap 'rm -f "$TMP"' EXIT
emit > "$TMP"

case "${MODE}" in
  dry-run) cat "$TMP" ;;
  check)
    rc=0
    if [[ ! -f "${OUT}" ]]; then echo "::error::[DRIFT-AGENTS-MD] ${OUT} missing — run: bash .claude/scripts/agents-md-gen.sh" >&2; exit 1; fi
    if ! diff -u "${OUT}" "$TMP" >/dev/null 2>&1; then
      echo "::error::[DRIFT-AGENTS-MD] AGENTS.md is stale vs its inputs. Regenerate: bash .claude/scripts/agents-md-gen.sh" >&2
      diff -u "${OUT}" "$TMP" >&2 || true; rc=1
    fi
    readme_consistency || rc=1
    [[ $rc -eq 0 ]] && echo "agents-md: AGENTS.md + README claims consistent ($(total_command_count) commands)."
    exit $rc ;;
  write)
    mv "$TMP" "${OUT}"; trap - EXIT
    CHK="${OUT}.checksum"   # checksum path derives from OUT (no decoupling)
    sha256_portable "${OUT}" | awk '{print $1}' > "${CHK}"
    [[ ${EMIT_JSON} -eq 1 ]] && echo "{\"output\":\"${OUT}\",\"checksum\":\"$(cat "${CHK}")\",\"version\":\"${SCRIPT_VERSION}\",\"total_commands\":$(total_command_count)}" >&2
    echo "agents-md: wrote ${OUT} (+ $(basename "${CHK}"))" ;;
esac
