#!/usr/bin/env bats
# OKF/ICM cycle Sprint 2 — agents-md-gen.sh (AGENTS.md generator) coverage.

setup() {
  BATS_TEST_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")" && pwd)"
  PROJECT_ROOT="$(cd "$BATS_TEST_DIR/../.." && pwd)"
  GEN="$PROJECT_ROOT/.claude/scripts/agents-md-gen.sh"
}

@test "agents-md-gen: --dry-run is byte-deterministic across two runs" {
  run bash "$GEN" --dry-run
  [ "$status" -eq 0 ]
  local a="$output"
  run bash "$GEN" --dry-run
  [ "$status" -eq 0 ]
  [ "$a" = "$output" ]
}

@test "agents-md-gen: --dry-run emits all 5 Golden Path commands + governance sections" {
  run bash "$GEN" --dry-run
  [ "$status" -eq 0 ]
  for c in /loa /plan /build /review /ship; do
    [[ "$output" == *"$c"* ]]
  done
  [[ "$output" == *"## Project Governance"* ]]
  [[ "$output" == *"NEVER"* ]]
  [[ "$output" == *"Three-Zone"* ]]
  [[ "$output" == *"known-failures.md"* ]]
}

@test "agents-md-gen: carries the generated sentinel (operator-detection exclusion)" {
  run bash "$GEN" --dry-run
  [ "$status" -eq 0 ]
  [[ "$(echo "$output" | head -1)" == *"generated by agents-md-gen.sh"* ]]
}

@test "agents-md-gen: command count == files minus golden-path excludes == 48" {
  local total excl computed
  total=$(find "$PROJECT_ROOT/.claude/commands" -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')
  excl=$(awk '/"excluded_from_count"[[:space:]]*:/{f=1} f{print} /\]/{if(f)exit}' \
    "$PROJECT_ROOT/.claude/data/golden-path.json" | grep -oE '"[a-z-]+"' | tr -d '"' | grep -vx excluded_from_count | grep -c .)
  computed=$(( total - excl ))
  [ "$computed" -eq 48 ]
  run bash "$GEN" --dry-run
  [[ "$output" == *"48 total commands"* ]]
}

@test "agents-md-gen: --check passes against the committed AGENTS.md" {
  run bash "$GEN" --check
  [ "$status" -eq 0 ]
}

@test "agents-md-gen: --check FAILS when AGENTS.md is tampered (drift detection)" {
  cp "$PROJECT_ROOT/AGENTS.md" "$BATS_TMPDIR/AGENTS.md.bak"
  printf '\nTAMPERED LINE\n' >> "$PROJECT_ROOT/AGENTS.md"
  run bash "$GEN" --check
  cp "$BATS_TMPDIR/AGENTS.md.bak" "$PROJECT_ROOT/AGENTS.md"   # restore before asserting
  [ "$status" -ne 0 ]
  [[ "$output" == *"DRIFT-AGENTS-MD"* ]]
}

@test "agents-md-gen: --check CATCHES /loa removed from the README Quick Start BLOCK (#1132, block-scoped)" {
  cp "$PROJECT_ROOT/README.md" "$BATS_TMPDIR/README.bak"
  # remove ONLY the Quick Start block /loa line; /loa still appears elsewhere in README
  grep -v '^/loa       # Where am I? Status, health, next step$' "$BATS_TMPDIR/README.bak" > "$PROJECT_ROOT/README.md"
  run bash "$GEN" --check
  cp "$BATS_TMPDIR/README.bak" "$PROJECT_ROOT/README.md"   # restore before asserting
  [ "$status" -ne 0 ]
  [[ "$output" == *"#1132"* ]]
}

@test "agents-md-gen: --check CATCHES a corrupted headline command count (#1135, anchored)" {
  cp "$PROJECT_ROOT/README.md" "$BATS_TMPDIR/README.bak"
  sed 's/\*\*48 total commands\.\*\*/**99 total commands.**/' "$BATS_TMPDIR/README.bak" > "$PROJECT_ROOT/README.md"
  run bash "$GEN" --check
  cp "$BATS_TMPDIR/README.bak" "$PROJECT_ROOT/README.md"
  [ "$status" -ne 0 ]
  [[ "$output" == *"#1135"* ]]
}
