#!/usr/bin/env bats
# OKF/ICM cycle Sprint 3 — grimoire-index.sh (cross-family knowledge index) coverage.

setup() {
  BATS_TEST_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")" && pwd)"
  PROJECT_ROOT="$(cd "$BATS_TEST_DIR/../.." && pwd)"
  GEN="$PROJECT_ROOT/.claude/scripts/grimoire-index.sh"
}

@test "grimoire-index: --json is valid JSON with families + counts + total" {
  run bash "$GEN" --json
  [ "$status" -eq 0 ]
  echo "$output" | jq -e '.families and .counts and (.total|type=="number")' >/dev/null
}

@test "grimoire-index: --json is byte-deterministic across two runs" {
  run bash "$GEN" --json; [ "$status" -eq 0 ]; local a="$output"
  run bash "$GEN" --json; [ "$status" -eq 0 ]; [ "$a" = "$output" ]
}

@test "grimoire-index: indexes KF from headings (complete) — KF-009 present even if absent from the Index table" {
  run bash "$GEN" --json
  [ "$status" -eq 0 ]
  # KF-009 has a ## KF-009: heading but is missing from the hand-maintained Index table
  echo "$output" | jq -e '.families.kf[] | select(.id=="KF-009")' >/dev/null
  # only KF + lore are git-tracked (vision/handoff/obs are gitignored local-only state,
  # absent in a fresh CI checkout); assert the tracked families + a non-empty index.
  echo "$output" | jq -e '(.counts.kf>0) and (.counts.lore>0) and (.total>0)' >/dev/null
}

@test "grimoire-index: --validate passes (integrity: every entry has id+path)" {
  run bash "$GEN" --validate
  [ "$status" -eq 0 ]
}

@test "grimoire-index: --validate WARNs on KF Index-table staleness (does not fail)" {
  run bash "$GEN" --validate
  [ "$status" -eq 0 ]
  [[ "$output" == *"Index table"* && "$output" == *"warning"* ]] || skip "KF Index table is in sync (no drift to warn about)"
}

@test "grimoire-index: observation entries get a synthesized obs-<hex> surrogate id" {
  run bash "$GEN" --json
  [ "$status" -eq 0 ]
  local obs_ct; obs_ct=$(echo "$output" | jq -r '.counts.obs // 0')
  if [ "$obs_ct" -gt 0 ]; then
    echo "$output" | jq -e '.families.obs[].id | test("^obs-[0-9a-f]{8}$")' >/dev/null
  fi
}

@test "grimoire-index: written INDEX.md has no control bytes (sanitization) + a generated sentinel" {
  bash "$GEN" --quiet
  run grep -nP '[\x00-\x08\x0e-\x1f]' "$PROJECT_ROOT/grimoires/loa/INDEX.md"
  [ "$status" -ne 0 ]   # grep finds nothing → control-byte-free
  run head -1 "$PROJECT_ROOT/grimoires/loa/INDEX.md"
  [[ "$output" == *"generated by grimoire-index.sh"* ]]
}
