#!/usr/bin/env bats
# OKF/ICM cycle Sprint 3 — grimoire-index.sh (cross-family knowledge index) coverage.

setup() {
  BATS_TEST_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")" && pwd)"
  PROJECT_ROOT="$(cd "$BATS_TEST_DIR/../.." && pwd)"
  GEN="$PROJECT_ROOT/.claude/scripts/grimoire-index.sh"
}

@test "grimoire-index: --json is valid JSON with families + counts + total" {
  run bash "$GEN" --json
  [ "$status" -eq 0 ]
  echo "$output" | jq -e '.families and .counts and (.total|type=="number")' >/dev/null
}

@test "grimoire-index: --json is byte-deterministic across two runs" {
  run bash "$GEN" --json; [ "$status" -eq 0 ]; local a="$output"
  run bash "$GEN" --json; [ "$status" -eq 0 ]; [ "$a" = "$output" ]
}

@test "grimoire-index: indexes KF from headings (complete) — KF-009 present even if absent from the Index table" {
  run bash "$GEN" --json
  [ "$status" -eq 0 ]
  # KF-009 has a ## KF-009: heading but is missing from the hand-maintained Index table
  echo "$output" | jq -e '.families.kf[] | select(.id=="KF-009")' >/dev/null
  # only KF + lore are git-tracked (vision/handoff/obs are gitignored local-only state,
  # absent in a fresh CI checkout); assert the tracked families + a non-empty index.
  echo "$output" | jq -e '(.counts.kf>0) and (.counts.lore>0) and (.total>0)' >/dev/null
}

@test "grimoire-index: --validate passes (integrity: every entry has id+path)" {
  run bash "$GEN" --validate
  [ "$status" -eq 0 ]
}

@test "grimoire-index: --validate FAILS when generated kf count != ## KF- heading count" {
  # cycle-115 D1 — the index-row-vs-heading check is now a fail-on-drift
  # assertion, not an informational ::warning::. The generated kf Index is
  # authoritative; if it cannot reproduce every ## KF- heading, validate fails.
  local dir; dir="$(mktemp -d)"
  mkdir -p "$dir/grimoires/loa" "$dir/.claude/scripts" "$dir/.run"
  cp "$GEN" "$dir/.claude/scripts/grimoire-index.sh"
  cp "$PROJECT_ROOT/.claude/scripts/compat-lib.sh" "$dir/.claude/scripts/compat-lib.sh"
  # Plant drift: two ## KF-001: headings — raw grep sees 2, generator dedupes to 1.
  {
    printf '# Known Failures\n\n## Index\n\n| ID | Status |\n|----|--------|\n'
    printf '## KF-001: first\n\n**Symptom**: a.\n**Recurrence count**: 1\n\n'
    printf '## KF-001: duplicate\n\n**Symptom**: b.\n**Recurrence count**: 2\n\n'
  } > "$dir/grimoires/loa/known-failures.md"
  run bash "$dir/.claude/scripts/grimoire-index.sh" --validate
  [ "$status" -ne 0 ]
}

@test "grimoire-index: observation entries get a synthesized obs-<hex> surrogate id" {
  run bash "$GEN" --json
  [ "$status" -eq 0 ]
  local obs_ct; obs_ct=$(echo "$output" | jq -r '.counts.obs // 0')
  if [ "$obs_ct" -gt 0 ]; then
    echo "$output" | jq -e '.families.obs[].id | test("^obs-[0-9a-f]{8}$")' >/dev/null
  fi
}

@test "grimoire-index: written INDEX.md has no control bytes (sanitization) + a generated sentinel" {
  bash "$GEN" --quiet
  run grep -nP '[\x00-\x08\x0e-\x1f]' "$PROJECT_ROOT/grimoires/loa/INDEX.md"
  [ "$status" -ne 0 ]   # grep finds nothing → control-byte-free
  run head -1 "$PROJECT_ROOT/grimoires/loa/INDEX.md"
  [[ "$output" == *"generated by grimoire-index.sh"* ]]
}
